front_right:
    ID: 1
    Return_Delay_Time: 0
    Operating_Mode: 4
    Profile_Acceleration: 0
    Profile_Velocity: 0

front_left:
    ID: 2
    Return_Delay_Time: 0
    Operating_Mode: 4
    Profile_Acceleration: 0
    Profile_Velocity: 0

back_right:
    ID: 3
    Return_Delay_Time: 0
    Operating_Mode: 4
    Profile_Acceleration: 0
    Profile_Velocity: 0

back_left:
    ID: 4
    Return_Delay_Time: 0
    Operating_Mode: 4
    Profile_Acceleration: 0
    Profile_Velocity: 0
